### ISSUE TITLE
Out of bounds index access

### ISSUE THREAD

**Issue by Nomadluap** [parkerduckworth/diskfrisk#37]
In file `config.c`, function `pull_file(char*)`: 

    char* pull_file(char *fname)
    {
        FILE *fp;
        char *buf;
        size_t sz;

        fp = fopen(fname, "r");
        fseek(fp, 0L, SEEK_END);
        sz = ftell(fp);

        // You are responsible for freeing 'buf' when it is passed to another function
        buf = malloc(sizeof(char) * sz + 1);
        *(buf + sz + 1) = '\0';

        rewind(fp);
        fread(buf, sz, 1, fp);

        if (fclose(fp) != 0)
            perror("fclose");
        return buf;
    }

You're allocating a char array of size sz+1, and then setting value `buf[sz+1]` to `\0`. This is an out-of-bounds access of the array. You probably meant `buf[sz] = '\0'` here. You're also not checking the return result of `fread` to ensure that all bytes were read successfully.

**Comment by parkerduckworth** [comment]
You are right, I will make the changes!

**Comment by parkerduckworth** [comment]
Fixed on pull request #44
