### ISSUE TITLE
Config file: Assuming that home directory is in default location.

### ISSUE THREAD

**Issue by Nomadluap** [parkerduckworth/diskfrisk#38]
When creating a path to store the config files for the program, the assumption is made that the user's home directory is stored under the default home path, which is not always the case. 

For example, on almost all Linux systems, as well as MacOS, the root user's home folder is stored at `/root` instead of the usual `/[home|Users]/root`. 

A better way to find the user's home directory is to read the `HOME` environment variable using the [`getenv`](http://pubs.opengroup.org/onlinepubs/009695399/functions/getenv.html) library function. 

Additionally the configuration directory under the user's home directory should by convention start with a `.` which will cause the directory to be hidden from most tools. This helps prevent clutter in the home directory.

**Comment by tavianator** [comment]
Even better than `$HOME` would be `getpwuid(getuid())->pw_dir`

**Comment by parkerduckworth** [comment]
Thank you both, I will make the changes!

**Comment by Nomadluap** [comment]
You could also use getpwuid()->pw_shell as the shell to exec in, instead of
hardcoding it to bash or whatever.

On Mon, Jul 16, 2018 at 11:10 AM, Parker Duckworth <notifications@github.com

**Comment by parkerduckworth** [comment]
Fixed on pull request #44 

Also, Nomadluap, I will add your suggestion of detecting the current shell type as an issue with an improvement label.  It is a good idea and rids of one more dependency.
